---
title: Basic Tools for NLP
description: This tutorial series is meant for LST/LCT Master's students interested in improving their technical skills.
semester: Basic Tools for NLP
instructors:
  - id: izaitova
    name: Iuliia Zaitova
    email: izaitova@lsv.uni-saarland.de
    web: https://sfb1102.uni-saarland.de/team/iuliia-zaitova/
  - id: rkumar
    name: Rishu Kumar
    email: riku00002@stud.uni-saarland.de
    web: https://rish.uk
  - id: chyek
    name: Chris Hyek
    email: chhy00001@stud.uni-saarland.de
baseurl: "/basic-tools-nlp-2023"
url: ""
---

# Welcome to Basic Tools for NLP!

This tutorial series is designed for LST/LCT Master's students who want to enhance their technical skills in natural language processing.

## Overview

[//]: # (TODO: Add an overview section)

## Instructors

Meet the instructors for this tutorial series:

{% for instructor in page.instructors %}
### {{ instructor.name }}

- Email: {{ instructor.email }}
- Website: [{{ instructor.web }}]({{ instructor.web }})
{% endfor %}

[//]: # (TODO: Add more content)
